### ISSUE TITLE
Missing HIPAA endpoint support.

### ISSUE THREAD

**Issue by ryleysevier** [jotform/jotform-api-python#17]
The HIPAA servers allow API access. An error is properly raised from the library for it either. It just kicks back saying content invalid.

**Comment by addisonlynch** [comment]
+1 on this

**Comment by utkubekci** [comment]
Hi,

We have been unable to replicate the issue you mentioned.

Can you please provide more details?

After setting the baseURL to https://hipaa-api.jotform.com using set_baseurl() function we did not encountered any issues and received the expected responses.
