### ISSUE TITLE
git:// is depreciated

### ISSUE THREAD

**Issue by ehawman-rosenberg** [jotform/jotform-api-python#19]
The current installation methods cite URLs with `git://`. This is no longer supported.

Attempting to install this way will result in a failure with "The unauthenticated git protocol on port 9418 is no longer supported."

**Comment by babakshirvani** [comment]
try https, worked for me

`    $ pip install git+https://github.com/jotform/jotform-api-python.git`

**Comment by ehawman-rosenberg** [comment]
It worked for me too! I should have just submitted a pull request. I'm doing it now.

**Comment by davidr-PA** [comment]
Thanks @babakshirvani that fixed it for me too.
