### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden 

### ISSUE THREAD

**Issue by DanielSkalar** [jotform/jotform-api-python#23]
I was getting always Error 403: Forbidden 

To fix add 'User-Agent': 'Mozilla/5.0' on the headers.
line 57

`        headers = {
            'apiKey': self.__apiKey,
            'User-Agent': 'Mozilla/5.0'
        }`

**Comment by ehawman** [comment]
This is happening for me as well. Adding that header didn't fix the issue, unfortunately.

**Comment by ehawman** [comment]
I created a pull request #24. Hopefully bugging support will get action taken.

**Comment by uelmalioglu** [comment]
Fixed in https://github.com/jotform/jotform-api-python/commit/462e7e644586828da846324e0d83cb3b8ef2bb1d
