### ISSUE TITLE
Client doesn't work in Europe

### ISSUE THREAD

**Issue by duffj** [jotform/jotform-api-python#3]
Hi, thanks for building this python client! Unfortunately it doesn't work in Europe because the `__baseUrl` is hardcoded to use the non-EU version of the API. I'll be submitting a pull request to fix the problem but I wanted to raise an issue here too for better traceability.

In case you're wondering, this is the output when executing `get_forms()` from a computer located in Europe:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    main()
  File "test.py", line 16, in main
    forms = jotformAPIClient.get_forms()
  File "/Users/dafydd/dev/personal/github/duffj/jotform-downloader/jotform-api-python/jotform.py", line 143, in get_forms
    return self.fetch_url('/user/forms', params, 'GET')
  File "/Users/dafydd/dev/personal/github/duffj/jotform-downloader/jotform-api-python/jotform.py", line 81, in fetch_url
    return responseObject['content']
KeyError: 'content'
```

**Comment by duffj** [comment]
Um, I tried pushing a branch to GitHub to raise a pull request for a fix for this issue, but I don't think I have permissions. Would it be possible to add me? I don't need access to push to `master`, just other branches would be great. 😄

**Comment by kenma9123** [comment]
Hi thanks for raising this issue. You can make a PR by forking this repository. Kindly visit this [guide](https://yangsu.github.io/pull-request-tutorial/)

**Comment by duffj** [comment]
Thanks! Done. Let me know if I haven't done it correctly.

**Comment by atleta** [comment]
Hmmm... PR still not accepted after half a year? Also, lib not updated for more than 3 years, documentation makes no mention of the API version it is compatible with, nor does the API doc states the current API version. Could you do something about it ASAP?

**Comment by kenma9123** [comment]
sorry about that, #5 merged
